export enum ActionType {
  CONNECT_WALLET = 'CONNECT_WALLET',
  SUFFICIENT_BALANCE = 'SUFFICIENT_BALANCE',
  DISCONNECT_WALLET = 'DISCONNECT_WALLET',
  PLATFORM_DISCONNECT_WALLET = 'PLATFORM_DISCONNECT_WALLET',
  MODAL_0PENED = 'MODAL_OPENED',
}
