export enum ActionType {
  // Transactions
  BATCH_TRANSACTIONS = 'BATCH_TRANSACTIONS',
  CLEAR_TX_LIST = 'CLEAR_TX_LIST',
  ADD_BATCH_TRANSACTION = 'ADD_BATCH_TRANSACTION',
  SET_PRE_CID_ADD = 'SET_PRE_CID_ADD',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  SUBSCRIBE = 'SUBSCRIBE',
}
