// Auth
export const CONNECT_WALLET = 'CONNECT_WALLET'
export const SUFFICIENT_BALANCE = 'SUFFICIENT_BALANCE'
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET'
export const PLATFORM_DISCONNECT_WALLET = 'PLATFORM_DISCONNECT_WALLET'
