import { BasciConnect } from 'components/ConnectWallet';
import useFaucet from 'hooks/useFaucet';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useAccount, useBalance, useNetwork } from 'wagmi';

const Home: NextPage = () => {
  const { chain } = useNetwork();
  const { isConnected, address } = useAccount();
  const { fundToken, fundInfo, isLoading, gasLimit } = useFaucet();

  return (
    <div className="h-screen w-full bg-gray-200">
      <Head>
        <title>Faucet</title>
        <meta name="description" content="Generated by create next wagmi dapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute top-5 right-10">
        <BasciConnect></BasciConnect>
      </div>

      <div className="mx-auto max-w-[1250px] pt-20"></div>
    </div>
  );
};

export default Home;
