/* eslint-disable react/button-has-type */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.scss';

import dynamic from 'next/dynamic';

const ConnectButton = dynamic(() => import('../components/Button/ConnectButton'), {
  ssr: false
});

const Home: NextPage = () => (
  <>
    <Head>
      <title>Turborepo Web3 Starter Kit</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.description}>
        <p>
          Get started by editing&nbsp;
          <code className={styles.code}>pages/index.js</code>
        </p>
        <ConnectButton />
      </div>

      <div className={styles.center}>
        <Image
          className={styles.logo}
          src="/turbo.svg"
          alt="Turborepo Logo"
          width={60}
          height={37}
          priority
        />
        <h1 className="mx-2 text-3xl font-semibold">Turborepo Web3 Starter Kit</h1>
      </div>

      <div className={styles.grid}>
        <a
          href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer">
          <h2>⚡ Application</h2>
          <p>
            A Next.js based app with typescript, wagmi, rainbowkit, <br />
            ether.js
          </p>
        </a>
        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer">
          <h2>⚡ Contracts Deployment</h2>
          <p>Production ready solidity contracts environment setup</p>
        </a>

        <a
          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer">
          <h2>📦 Config management</h2>
          <p>Lint and common config configurations throughout the monorepo</p>
        </a>

        <a
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer">
          <h2>🌱 Test Driven Environment</h2>
          <p>Complete test driven environment for multi purpose</p>
        </a>
      </div>
    </main>
  </>
);

export default Home;
