export enum ActionType {
  // Transactions
  TRANSACTIONS = 'TRANSACTIONS',
  CLEAR_TX_LIST = 'CLEAR_TX_LIST',
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  SET_PRE_CID_ADD = 'SET_PRE_CID_ADD',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  SUBSCRIBE = 'SUBSCRIBE',
}
